### PR TITLE
add client validation

### PR DESCRIPTION
**Pull request by wkf928592**
Add client validation

### CODE REVIEW

**Comment by Borales** [comment]
@wkf928592 great, thanks! have you tested it?

**Comment by Borales** [comment]
@wkf928592 I will check if it won't interrupt with https://github.com/Borales/yii2-phone-input/blob/master/src/PhoneInput.php#L29

**Comment by wkf928592** [comment]
@Borales Yes, I tested！It works perfect！You can view online DEMO:[http://jackocnr.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html](url)

**Comment by Borales** [comment]
@wkf928592 sorry, those are 2 different things, so of course it won't interrupt each other.
Thanks!

**Pull request merged**
